export const CITIES = [
    {
      city: 'Athens',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '729137',
      iso2: 'GR',
      capital: 'primary',
      lat: '37.983333',
      lng: '23.733333',
      population: '3242000'
    },
    {
      city: 'Thessaloníki',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '354290',
      iso2: 'GR',
      capital: 'admin',
      lat: '40.643615',
      lng: '22.930864',
      population: '828000'
    },
    {
      city: 'Piraeus',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '175697',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.961389',
      lng: '23.638889',
      population: '466065'
    },
    {
      city: 'Pátra',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '155799',
      iso2: 'GR',
      capital: 'admin',
      lat: '38.244444',
      lng: '21.734444',
      population: '163360'
    },
    {
      city: 'Irákleio',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '131654',
      iso2: 'GR',
      capital: 'admin',
      lat: '35.338082',
      lng: '25.133029',
      population: '137154'
    },
    {
      city: 'Lárisa',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '111487',
      iso2: 'GR',
      capital: 'admin',
      lat: '39.636889',
      lng: '22.417611',
      population: '128758'
    },
    {
      city: 'Áno Vólos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '84425',
      iso2: 'GR',
      capital: '',
      lat: '39.379361',
      lng: '22.981806',
      population: '110632'
    },
    {
      city: 'Ioánnina',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '64012',
      iso2: 'GR',
      capital: 'admin',
      lat: '39.664861',
      lng: '20.851889',
      population: '86304'
    },
    {
      city: 'Chaniá',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '54565',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.511236',
      lng: '24.02921',
      population: '78728'
    },
    {
      city: 'Agrínio',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '43525',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.621889',
      lng: '21.409778',
      population: '75233'
    },
    {
      city: 'Chalkída',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '54558',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.461451',
      lng: '23.602631',
      population: '71842'
    },
    {
      city: 'Kalámi',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '51108',
      iso2: 'GR',
      capital: '',
      lat: '37.062286',
      lng: '22.070569',
      population: '71823'
    },
    {
      city: 'Kavála',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '52950',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.939586',
      lng: '24.406868',
      population: '59240'
    },
    {
      city: 'Ródos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '56128',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.435564',
      lng: '28.221985',
      population: '56969'
    },
    {
      city: 'Sérres',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '45935',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.084991',
      lng: '23.54757',
      population: '55886'
    },
    {
      city: 'Kateríni',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '48408',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.269557',
      lng: '22.506078',
      population: '53293'
    },
    {
      city: 'Alexandroúpoli',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '44444',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.849949',
      lng: '25.876435',
      population: '52979'
    },
    {
      city: 'Xánthi',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '48221',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.134876',
      lng: '24.887998',
      population: '50570'
    },
    {
      city: 'Lamía',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '47246',
      iso2: 'GR',
      capital: 'admin',
      lat: '38.9',
      lng: '22.433333',
      population: '47246'
    },
    {
      city: 'Komotiní',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '45631',
      iso2: 'GR',
      capital: 'admin',
      lat: '41.119174',
      lng: '25.40535',
      population: '45631'
    },
    {
      city: 'Kérkyra',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '27003',
      iso2: 'GR',
      capital: 'admin',
      lat: '39.620694',
      lng: '19.91975',
      population: '38517'
    },
    {
      city: 'Mytilíni',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '28322',
      iso2: 'GR',
      capital: 'admin',
      lat: '39.11',
      lng: '26.554722',
      population: '29328'
    },
    {
      city: 'Trípoli',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '26561',
      iso2: 'GR',
      capital: 'admin',
      lat: '37.508889',
      lng: '22.379444',
      population: '28970'
    },
    {
      city: 'Chíos',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '23953',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.368621',
      lng: '26.132356',
      population: '26891'
    },
    {
      city: 'Pýrgos',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '22223',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.672139',
      lng: '21.439306',
      population: '22399'
    },
    {
      city: 'Kos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '18691',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.892607',
      lng: '27.287574',
      population: '19244'
    },
    {
      city: 'Spárti',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '15497',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.074459',
      lng: '22.430091',
      population: '16187'
    },
    {
      city: 'Ermoúpoli',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '12260',
      iso2: 'GR',
      capital: 'admin',
      lat: '37.45',
      lng: '24.933333',
      population: '12260'
    },
    {
      city: 'Siteía',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '8707',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.208507',
      lng: '26.103024',
      population: '8833'
    },
    {
      city: 'Polýgyros',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '5258',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.37704',
      lng: '23.441354',
      population: '5258'
    },
    {
      city: 'Megalópoli',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.401421',
      lng: '22.13689',
      population: ''
    },
    {
      city: 'Cholargós',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.00095',
      lng: '23.80079',
      population: ''
    },
    {
      city: 'Náousa',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.630001',
      lng: '22.068374',
      population: ''
    },
    {
      city: 'Ágios Nikólaos',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.191064',
      lng: '25.715244',
      population: ''
    },
    {
      city: 'Agía Kyriakí',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.522639',
      lng: '20.883583',
      population: ''
    },
    {
      city: 'Póros',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.500076',
      lng: '23.454955',
      population: ''
    },
    {
      city: 'Palaió Fáliro',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.930198',
      lng: '23.702602',
      population: ''
    },
    {
      city: 'Palaióchora',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.231328',
      lng: '23.681271',
      population: ''
    },
    {
      city: 'Melíssia',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.051158',
      lng: '23.836204',
      population: ''
    },
    {
      city: 'Agía Marína',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.154351',
      lng: '26.855903',
      population: ''
    },
    {
      city: 'Íos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.723273',
      lng: '25.28246',
      population: ''
    },
    {
      city: 'Níkiti',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.229439',
      lng: '23.67149',
      population: ''
    },
    {
      city: 'Ílion',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.032332',
      lng: '23.702161',
      population: ''
    },
    {
      city: 'Kastrí',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '34.83453',
      lng: '24.086424',
      population: ''
    },
    {
      city: 'Kárystos',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.016833',
      lng: '24.421111',
      population: ''
    },
    {
      city: 'Pezá',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.21806',
      lng: '25.192926',
      population: ''
    },
    {
      city: 'Kalamáta',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.035586',
      lng: '22.112982',
      population: ''
    },
    {
      city: 'Itháki',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.362583',
      lng: '20.721833',
      population: ''
    },
    {
      city: 'Mandráki',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.61038',
      lng: '27.132234',
      population: ''
    },
    {
      city: 'Asprópyrgos',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.061713',
      lng: '23.589444',
      population: ''
    },
    {
      city: 'Geráni',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.516772',
      lng: '23.878027',
      population: ''
    },
    {
      city: 'Paranésti',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.266801',
      lng: '24.501991',
      population: ''
    },
    {
      city: 'Kálymnos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.95258',
      lng: '26.980644',
      population: ''
    },
    {
      city: 'Kyparissía',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.250733',
      lng: '21.669551',
      population: ''
    },
    {
      city: 'Výronas',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.959554',
      lng: '23.752897',
      population: ''
    },
    {
      city: 'Pérama',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.369525',
      lng: '24.703879',
      population: ''
    },
    {
      city: 'Pérama',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.966223',
      lng: '23.573917',
      population: ''
    },
    {
      city: 'Zográfos',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.975744',
      lng: '23.769113',
      population: ''
    },
    {
      city: 'Mílos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.743605',
      lng: '24.422496',
      population: ''
    },
    {
      city: 'Thérmi',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.547953',
      lng: '23.020184',
      population: ''
    },
    {
      city: 'Áno Kalentíni',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.251528',
      lng: '21.167944',
      population: ''
    },
    {
      city: 'Alíartos',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.372662',
      lng: '23.101288',
      population: ''
    },
    {
      city: 'Asklipieío',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.5975',
      lng: '23.074736',
      population: ''
    },
    {
      city: 'Igoumenítsa',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.503417',
      lng: '20.267278',
      population: ''
    },
    {
      city: 'Sofádes',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.334365',
      lng: '22.097337',
      population: ''
    },
    {
      city: 'Kastélli',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.208387',
      lng: '25.338395',
      population: ''
    },
    {
      city: 'Íasmos',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.127895',
      lng: '25.184382',
      population: ''
    },
    {
      city: 'Spáta',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.962471',
      lng: '23.915008',
      population: ''
    },
    {
      city: 'Árgos Orestikó',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.452491',
      lng: '21.259247',
      population: ''
    },
    {
      city: 'Argostóli',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.172889',
      lng: '20.490278',
      population: ''
    },
    {
      city: 'Lefkáda',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.830361',
      lng: '20.704417',
      population: ''
    },
    {
      city: 'Néa Smýrni',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.945391',
      lng: '23.714586',
      population: ''
    },
    {
      city: 'Mégara',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.995758',
      lng: '23.344661',
      population: ''
    },
    {
      city: 'Atalánti',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.653951',
      lng: '22.997011',
      population: ''
    },
    {
      city: 'Alexándreia',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.627594',
      lng: '22.444484',
      population: ''
    },
    {
      city: 'Dáfni',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.950051',
      lng: '23.731164',
      population: ''
    },
    {
      city: 'Astakós',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.537498',
      lng: '21.084073',
      population: ''
    },
    {
      city: 'Tzermiádo',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.199062',
      lng: '25.48892',
      population: ''
    },
    {
      city: 'Neméa',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.819764',
      lng: '22.662855',
      population: ''
    },
    {
      city: 'Kilkís',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.99302',
      lng: '22.874331',
      population: ''
    },
    {
      city: 'Kalávryta',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.031944',
      lng: '22.110833',
      population: ''
    },
    {
      city: 'Ierápetra',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.010563',
      lng: '25.739502',
      population: ''
    },
    {
      city: 'Ierissós',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.397723',
      lng: '23.877716',
      population: ''
    },
    {
      city: 'Orestiáda',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.506043',
      lng: '26.529641',
      population: ''
    },
    {
      city: 'Kaména Voúrla',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.780599',
      lng: '22.788433',
      population: ''
    },
    {
      city: 'Skýdra',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.767621',
      lng: '22.156474',
      population: ''
    },
    {
      city: 'Árgos',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.635035',
      lng: '22.728503',
      population: ''
    },
    {
      city: 'Peristéri',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.009396',
      lng: '23.693942',
      population: ''
    },
    {
      city: 'Aigínio',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.499666',
      lng: '22.542147',
      population: ''
    },
    {
      city: 'Maroúsi',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.053661',
      lng: '23.807692',
      population: ''
    },
    {
      city: 'Péta',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.167673',
      lng: '21.035102',
      population: ''
    },
    {
      city: 'Sykiés',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.647372',
      lng: '22.956349',
      population: ''
    },
    {
      city: 'Néa Zíchni',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.031224',
      lng: '23.828941',
      population: ''
    },
    {
      city: 'Giannitsá',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.792367',
      lng: '22.414839',
      population: ''
    },
    {
      city: 'Mouzáki',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.428778',
      lng: '21.662889',
      population: ''
    },
    {
      city: 'Velestíno',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.382081',
      lng: '22.745136',
      population: ''
    },
    {
      city: 'Pýlos',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.912844',
      lng: '21.696644',
      population: ''
    },
    {
      city: 'Káto Achaḯa',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.142028',
      lng: '21.550736',
      population: ''
    },
    {
      city: 'Vrilíssia',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.035407',
      lng: '23.831943',
      population: ''
    },
    {
      city: 'Galatás',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.496076',
      lng: '23.448066',
      population: ''
    },
    {
      city: 'Kónitsa',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.046135',
      lng: '20.750396',
      population: ''
    },
    {
      city: 'Chalandrítsa',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.106616',
      lng: '21.783201',
      population: ''
    },
    {
      city: 'Deskáti',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.925272',
      lng: '21.810152',
      population: ''
    },
    {
      city: 'Vrýses',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.454507',
      lng: '23.6004',
      population: ''
    },
    {
      city: 'Síkinos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.696522',
      lng: '25.119876',
      population: ''
    },
    {
      city: 'Kifisiá',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.076703',
      lng: '23.820776',
      population: ''
    },
    {
      city: 'Salamína',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.966546',
      lng: '23.491851',
      population: ''
    },
    {
      city: 'Spétses',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.263875',
      lng: '23.155469',
      population: ''
    },
    {
      city: 'Páros',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.084355',
      lng: '25.149176',
      population: ''
    },
    {
      city: 'Skiáthos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.165333',
      lng: '23.487306',
      population: ''
    },
    {
      city: 'Fillýra',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.121566',
      lng: '25.632418',
      population: ''
    },
    {
      city: 'Amýntaio',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.69033',
      lng: '21.679623',
      population: ''
    },
    {
      city: 'Alivéri',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.410028',
      lng: '24.03825',
      population: ''
    },
    {
      city: 'Sidirókastro',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.236068',
      lng: '23.39248',
      population: ''
    },
    {
      city: 'Néa Ionía',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.04142',
      lng: '23.752898',
      population: ''
    },
    {
      city: 'Ágios Kírykos',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.612872',
      lng: '26.291092',
      population: ''
    },
    {
      city: 'Sápes',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.024762',
      lng: '25.696501',
      population: ''
    },
    {
      city: 'Rodolívos',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.921054',
      lng: '23.974641',
      population: ''
    },
    {
      city: 'Polýkastro',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.997539',
      lng: '22.570945',
      population: ''
    },
    {
      city: 'Filippiáda',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.204333',
      lng: '20.881583',
      population: ''
    },
    {
      city: 'Irákleio',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.053994',
      lng: '23.77449',
      population: ''
    },
    {
      city: 'Irákleia',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.182276',
      lng: '23.282221',
      population: ''
    },
    {
      city: 'Thebes',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.319927',
      lng: '23.319074',
      population: ''
    },
    {
      city: 'Marathónas',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.156533',
      lng: '23.959951',
      population: ''
    },
    {
      city: 'Gázi',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.32517',
      lng: '25.066222',
      population: ''
    },
    {
      city: 'Sérifos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.15',
      lng: '24.5',
      population: ''
    },
    {
      city: 'Kórinthos',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.938465',
      lng: '22.927911',
      population: ''
    },
    {
      city: 'Litóchoro',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.098648',
      lng: '22.505356',
      population: ''
    },
    {
      city: 'Ampelókipoi',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.654038',
      lng: '22.91747',
      population: ''
    },
    {
      city: 'Loutráki',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.975001',
      lng: '22.979761',
      population: ''
    },
    {
      city: 'Álimos',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.914335',
      lng: '23.715868',
      population: ''
    },
    {
      city: 'Kalamariá',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.578948',
      lng: '22.948475',
      population: ''
    },
    {
      city: 'Amfilochía',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.862365',
      lng: '21.166047',
      population: ''
    },
    {
      city: 'Mándra',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.0747',
      lng: '23.496944',
      population: ''
    },
    {
      city: 'Zákynthos',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.780221',
      lng: '20.895551',
      population: ''
    },
    {
      city: 'Sámos',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.757437',
      lng: '26.976157',
      population: ''
    },
    {
      city: 'Náfplio',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.568632',
      lng: '22.806912',
      population: ''
    },
    {
      city: 'Folégandros',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.62803',
      lng: '24.919944',
      population: ''
    },
    {
      city: 'Elassóna',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.892889',
      lng: '22.188778',
      population: ''
    },
    {
      city: 'Acharnés',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.084728',
      lng: '23.73718',
      population: ''
    },
    {
      city: 'Spercheiáda',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.908669',
      lng: '22.126835',
      population: ''
    },
    {
      city: 'Métsovo',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.771247',
      lng: '21.183299',
      population: ''
    },
    {
      city: 'Ágios Efstrátios',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.539104',
      lng: '24.990445',
      population: ''
    },
    {
      city: 'Ándros',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.833333',
      lng: '24.933333',
      population: ''
    },
    {
      city: 'Palamás',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.464439',
      lng: '22.08249',
      population: ''
    },
    {
      city: 'Xylókastro',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.07712',
      lng: '22.633146',
      population: ''
    },
    {
      city: 'Istiaía',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.954437',
      lng: '23.149986',
      population: ''
    },
    {
      city: 'Megálo Chorió',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.455083',
      lng: '27.346892',
      population: ''
    },
    {
      city: 'Amaliáda',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.797167',
      lng: '21.349528',
      population: ''
    },
    {
      city: 'Psychikó',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.013057',
      lng: '23.772304',
      population: ''
    },
    {
      city: 'Tríkala',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.554926',
      lng: '21.768369',
      population: ''
    },
    {
      city: 'Évlalo',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.981235',
      lng: '24.800107',
      population: ''
    },
    {
      city: 'Évosmos',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.669775',
      lng: '22.90879',
      population: ''
    },
    {
      city: 'Leonídio',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.167704',
      lng: '22.858153',
      population: ''
    },
    {
      city: 'Goúrnes',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.324771',
      lng: '25.277567',
      population: ''
    },
    {
      city: 'Dístomo',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.42889',
      lng: '22.666746',
      population: ''
    },
    {
      city: 'Paianía',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.95432',
      lng: '23.854138',
      population: ''
    },
    {
      city: 'Lidoríki',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.527359',
      lng: '22.205085',
      population: ''
    },
    {
      city: 'Alónnisos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.149361',
      lng: '23.845361',
      population: ''
    },
    {
      city: 'Psará',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.541441',
      lng: '25.563014',
      population: ''
    },
    {
      city: 'Dráma',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.152831',
      lng: '24.147302',
      population: ''
    },
    {
      city: 'Prosotsáni',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.179377',
      lng: '23.971968',
      population: ''
    },
    {
      city: 'Skópelos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.121667',
      lng: '23.727556',
      population: ''
    },
    {
      city: 'Chaïdári',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.007868',
      lng: '23.659713',
      population: ''
    },
    {
      city: 'Antíparos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.040429',
      lng: '25.08188',
      population: ''
    },
    {
      city: 'Péfki',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.055583',
      lng: '23.79032',
      population: ''
    },
    {
      city: 'Kranídi',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.37963',
      lng: '23.159581',
      population: ''
    },
    {
      city: 'Préveza',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.956167',
      lng: '20.7505',
      population: ''
    },
    {
      city: 'Káto Nevrokópi',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.342114',
      lng: '23.868228',
      population: ''
    },
    {
      city: 'Zevgolatió',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.081529',
      lng: '22.619325',
      population: ''
    },
    {
      city: 'Archaía Olympía',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.646917',
      lng: '21.625639',
      population: ''
    },
    {
      city: 'Psachná',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.577536',
      lng: '23.643107',
      population: ''
    },
    {
      city: 'Siátista',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.258261',
      lng: '21.552513',
      population: ''
    },
    {
      city: 'Áno Sýros',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.45',
      lng: '24.933333',
      population: ''
    },
    {
      city: 'Ágioi Déka',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.058216',
      lng: '24.960236',
      population: ''
    },
    {
      city: 'Vólos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.373027',
      lng: '22.942708',
      population: ''
    },
    {
      city: 'Korydallós',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.981097',
      lng: '23.651351',
      population: ''
    },
    {
      city: 'Néa Filadélfeia',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.041867',
      lng: '23.7415',
      population: ''
    },
    {
      city: 'Eleftheroúpoli',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.914913',
      lng: '24.254241',
      population: ''
    },
    {
      city: 'Kýthira',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.149229',
      lng: '22.987954',
      population: ''
    },
    {
      city: 'Smínthi',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.228866',
      lng: '24.880445',
      population: ''
    },
    {
      city: 'Áno Liósia',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.084017',
      lng: '23.702293',
      population: ''
    },
    {
      city: 'Rafína',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.023207',
      lng: '24.002594',
      population: ''
    },
    {
      city: 'Kalývia Thorikoú',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.839079',
      lng: '23.927634',
      population: ''
    },
    {
      city: 'Chrysó',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.058377',
      lng: '23.651399',
      population: ''
    },
    {
      city: 'Gérakas',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.013336',
      lng: '23.855994',
      population: ''
    },
    {
      city: 'Édessa',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.802596',
      lng: '22.047514',
      population: ''
    },
    {
      city: 'Náfpaktos',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.393798',
      lng: '21.828368',
      population: ''
    },
    {
      city: 'Chóra Sfakíon',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.201807',
      lng: '24.139826',
      population: ''
    },
    {
      city: 'Kímolos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.793743',
      lng: '24.573874',
      population: ''
    },
    {
      city: 'Ilioúpoli',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.930202',
      lng: '23.751406',
      population: ''
    },
    {
      city: 'Kerasochóri',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.0045',
      lng: '21.639028',
      population: ''
    },
    {
      city: 'Náxos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.102069',
      lng: '25.378035',
      population: ''
    },
    {
      city: 'Dimitsána',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.595672',
      lng: '22.039477',
      population: ''
    },
    {
      city: 'Nestório',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.413386',
      lng: '21.061162',
      population: ''
    },
    {
      city: 'Metamórfosi',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.063904',
      lng: '23.761847',
      population: ''
    },
    {
      city: 'Moscháto',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.954043',
      lng: '23.681454',
      population: ''
    },
    {
      city: 'Kréstena',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.591528',
      lng: '21.617833',
      population: ''
    },
    {
      city: 'Prámanta',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.52198',
      lng: '21.098563',
      population: ''
    },
    {
      city: 'Límni',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.765902',
      lng: '23.31946',
      population: ''
    },
    {
      city: 'Meligalás',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.223725',
      lng: '21.96988',
      population: ''
    },
    {
      city: 'Anógeia',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.290667',
      lng: '24.883421',
      population: ''
    },
    {
      city: 'Paramythiá',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.465417',
      lng: '20.513028',
      population: ''
    },
    {
      city: 'Peraía',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.499003',
      lng: '22.926167',
      population: ''
    },
    {
      city: 'Kaisarianí',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.968142',
      lng: '23.759457',
      population: ''
    },
    {
      city: 'Leipsoí',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.295857',
      lng: '26.769537',
      population: ''
    },
    {
      city: 'Fársala',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.296306',
      lng: '22.384472',
      population: ''
    },
    {
      city: 'Kéa',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.633333',
      lng: '24.35',
      population: ''
    },
    {
      city: 'Anthiró',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.34725',
      lng: '21.458556',
      population: ''
    },
    {
      city: 'Aigáleo',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.992527',
      lng: '23.678064',
      population: ''
    },
    {
      city: 'Lagkadás',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.750484',
      lng: '23.065161',
      population: ''
    },
    {
      city: 'Eleoúsa',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.705861',
      lng: '20.79275',
      population: ''
    },
    {
      city: 'Anáfi',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.350868',
      lng: '25.767118',
      population: ''
    },
    {
      city: 'Argalastí',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.226139',
      lng: '23.217333',
      population: ''
    },
    {
      city: 'Livadeiá',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.436158',
      lng: '22.87665',
      population: ''
    },
    {
      city: 'Kanaláki',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.233056',
      lng: '20.603139',
      population: ''
    },
    {
      city: 'Skýros',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.906011',
      lng: '24.56556',
      population: ''
    },
    {
      city: 'Makrychóri',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.804194',
      lng: '22.492278',
      population: ''
    },
    {
      city: 'Ýdra',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.346946',
      lng: '23.465725',
      population: ''
    },
    {
      city: 'Didymóteicho',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.350129',
      lng: '26.498022',
      population: ''
    },
    {
      city: 'Kastoriá',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.521648',
      lng: '21.263407',
      population: ''
    },
    {
      city: 'Thásos',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.778353',
      lng: '24.709417',
      population: ''
    },
    {
      city: 'Karpenísi',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.912178',
      lng: '21.798362',
      population: ''
    },
    {
      city: 'Pýli',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.459606',
      lng: '21.622123',
      population: ''
    },
    {
      city: 'Zagorá',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.444417',
      lng: '23.101167',
      population: ''
    },
    {
      city: 'Farkadóna',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.59133',
      lng: '22.068624',
      population: ''
    },
    {
      city: 'Kardítsa',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.364848',
      lng: '21.921912',
      population: ''
    },
    {
      city: 'Frý',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.416178',
      lng: '26.9231',
      population: ''
    },
    {
      city: 'Aígina',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.747641',
      lng: '23.43211',
      population: ''
    },
    {
      city: 'Lechainá',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.937306',
      lng: '21.262139',
      population: ''
    },
    {
      city: 'Erétria',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.394338',
      lng: '23.794968',
      population: ''
    },
    {
      city: 'Elefsína',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.045194',
      lng: '23.543821',
      population: ''
    },
    {
      city: 'Kiáto',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.011807',
      lng: '22.749725',
      population: ''
    },
    {
      city: 'Gastoúni',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.850583',
      lng: '21.253389',
      population: ''
    },
    {
      city: 'Káto Tithoréa',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.608621',
      lng: '22.712961',
      population: ''
    },
    {
      city: 'Ágioi Anárgyroi',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.032449',
      lng: '23.724739',
      population: ''
    },
    {
      city: 'Spíli',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.216798',
      lng: '24.536112',
      population: ''
    },
    {
      city: 'Amorgós',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.831809',
      lng: '25.898313',
      population: ''
    },
    {
      city: 'Agiá',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.71875',
      lng: '22.755528',
      population: ''
    },
    {
      city: 'Agía Foteiní',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.254212',
      lng: '24.634203',
      population: ''
    },
    {
      city: 'Thérmo',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.572861',
      lng: '21.666167',
      population: ''
    },
    {
      city: 'Oropós',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.301722',
      lng: '23.754167',
      population: ''
    },
    {
      city: 'Koropí',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.900859',
      lng: '23.872306',
      population: ''
    },
    {
      city: 'Oinoússes',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.515768',
      lng: '26.222474',
      population: ''
    },
    {
      city: 'Morfovoúni',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.352528',
      lng: '21.750435',
      population: ''
    },
    {
      city: 'Panórama',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.585316',
      lng: '23.028138',
      population: ''
    },
    {
      city: 'Oraiókastro',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.729566',
      lng: '22.916548',
      population: ''
    },
    {
      city: 'Kozáni',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'admin',
      lat: '40.300685',
      lng: '21.788959',
      population: ''
    },
    {
      city: 'Elafónisos',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.509021',
      lng: '22.978682',
      population: ''
    },
    {
      city: 'Grevená',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.084021',
      lng: '21.429096',
      population: ''
    },
    {
      city: 'Skála',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.852386',
      lng: '22.666515',
      population: ''
    },
    {
      city: 'Árta',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.160139',
      lng: '20.985611',
      population: ''
    },
    {
      city: 'Kassándreia',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.048701',
      lng: '23.413064',
      population: ''
    },
    {
      city: 'Kalampáka',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.706184',
      lng: '21.626047',
      population: ''
    },
    {
      city: 'Kalampáki',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.051399',
      lng: '24.1871',
      population: ''
    },
    {
      city: 'Sými',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.614478',
      lng: '27.836224',
      population: ''
    },
    {
      city: 'Orchomenós',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.492114',
      lng: '22.978681',
      population: ''
    },
    {
      city: 'Kárpathos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.506479',
      lng: '27.21301',
      population: ''
    },
    {
      city: 'Schimatári',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.346528',
      lng: '23.581229',
      population: ''
    },
    {
      city: 'Chrysoúpoli',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.986661',
      lng: '24.699648',
      population: ''
    },
    {
      city: 'Voúla',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.845901',
      lng: '23.762577',
      population: ''
    },
    {
      city: 'Filiátes',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.600056',
      lng: '20.309167',
      population: ''
    },
    {
      city: 'Sérvia',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.184385',
      lng: '22.000485',
      population: ''
    },
    {
      city: 'Tínos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.537531',
      lng: '25.163434',
      population: ''
    },
    {
      city: 'Týrnavos',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.740333',
      lng: '22.286889',
      population: ''
    },
    {
      city: 'Koufália',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.779878',
      lng: '22.57781',
      population: ''
    },
    {
      city: 'Samothráki',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.474338',
      lng: '25.525137',
      population: ''
    },
    {
      city: 'Asprángeloi',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.822639',
      lng: '20.727639',
      population: ''
    },
    {
      city: 'Argyroúpoli',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.906165',
      lng: '23.750712',
      population: ''
    },
    {
      city: 'Agía Paraskeví',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.013637',
      lng: '23.825535',
      population: ''
    },
    {
      city: 'Aígio',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.249322',
      lng: '22.084838',
      population: ''
    },
    {
      city: 'Ágios Dimítrios',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.934177',
      lng: '23.729145',
      population: ''
    },
    {
      city: 'Galátsi',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.013005',
      lng: '23.753293',
      population: ''
    },
    {
      city: 'Astypálaia',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.547904',
      lng: '26.351977',
      population: ''
    },
    {
      city: 'Ámfissa',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.52813',
      lng: '22.377131',
      population: ''
    },
    {
      city: 'Gýtheio',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.762071',
      lng: '22.563789',
      population: ''
    },
    {
      city: 'Megísti',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.148344',
      lng: '29.591655',
      population: ''
    },
    {
      city: 'Geniséa',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.060476',
      lng: '24.961796',
      population: ''
    },
    {
      city: 'Markópoulo',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.883333',
      lng: '23.933333',
      population: ''
    },
    {
      city: 'Stavroúpoli',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.669203',
      lng: '22.931033',
      population: ''
    },
    {
      city: 'Zacháro',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.483583',
      lng: '21.6495',
      population: ''
    },
    {
      city: 'Agía Varvára',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.988313',
      lng: '23.660925',
      population: ''
    },
    {
      city: 'Megálo Chorió',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.457757',
      lng: '26.972355',
      population: ''
    },
    {
      city: 'Véroia',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.524368',
      lng: '22.202419',
      population: ''
    },
    {
      city: 'Moláoi',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.804176',
      lng: '22.853346',
      population: ''
    },
    {
      city: 'Mýkonos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.45',
      lng: '25.333333',
      population: ''
    },
    {
      city: 'Apollonía',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.974373',
      lng: '24.724006',
      population: ''
    },
    {
      city: 'Réthymno',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.366868',
      lng: '24.474872',
      population: ''
    },
    {
      city: 'Chalándri',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.021559',
      lng: '23.798919',
      population: ''
    },
    {
      city: 'Gáios',
      admin: 'Ionía Nísia',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.196083',
      lng: '20.185778',
      population: ''
    },
    {
      city: 'Mesolóngi',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.371378',
      lng: '21.431509',
      population: ''
    },
    {
      city: 'Flórina',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.78071',
      lng: '21.409274',
      population: ''
    },
    {
      city: 'Stylída',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.914429',
      lng: '22.613769',
      population: ''
    },
    {
      city: 'Laimós',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.835876',
      lng: '21.140355',
      population: ''
    },
    {
      city: 'Moíres',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.051684',
      lng: '24.875012',
      population: ''
    },
    {
      city: 'Kallithéa',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.954953',
      lng: '23.701001',
      population: ''
    },
    {
      city: 'Souflí',
      admin: 'Anatolikí Makedonía kai Thráki',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '41.194824',
      lng: '26.300171',
      population: ''
    },
    {
      city: 'Messíni',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.051106',
      lng: '22.008423',
      population: ''
    },
    {
      city: 'Firá',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.420718',
      lng: '25.43219',
      population: ''
    },
    {
      city: 'Pátmos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.308646',
      lng: '26.547423',
      population: ''
    },
    {
      city: 'Lávrio',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.714389',
      lng: '24.053278',
      population: ''
    },
    {
      city: 'Kalpáki',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.887056',
      lng: '20.624944',
      population: ''
    },
    {
      city: 'Domokós',
      admin: 'Stereá Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.127459',
      lng: '22.303834',
      population: ''
    },
    {
      city: 'Stavrós',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.663545',
      lng: '23.699785',
      population: ''
    },
    {
      city: 'Agkístri',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.709586',
      lng: '23.347153',
      population: ''
    },
    {
      city: 'Vourgaréli',
      admin: 'Ípeiros',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.37175',
      lng: '21.183306',
      population: ''
    },
    {
      city: 'Keratsíni',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.964318',
      lng: '23.619906',
      population: ''
    },
    {
      city: 'Foúrnoi',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.576824',
      lng: '26.481504',
      population: ''
    },
    {
      city: 'Kýthnos',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.416667',
      lng: '24.433333',
      population: ''
    },
    {
      city: 'Mýrina',
      admin: 'Voreío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.879478',
      lng: '25.065005',
      population: ''
    },
    {
      city: 'Níkaia',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.564944',
      lng: '22.466',
      population: ''
    },
    {
      city: 'Ágios Stéfanos',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.140834',
      lng: '23.859089',
      population: ''
    },
    {
      city: 'Néa Moudaniá',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.241123',
      lng: '23.286565',
      population: ''
    },
    {
      city: 'Kardamýli',
      admin: 'Peloponnísos',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.88769',
      lng: '22.232668',
      population: ''
    },
    {
      city: 'Petroúpoli',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.039568',
      lng: '23.681172',
      population: ''
    },
    {
      city: 'Aridaía',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.973004',
      lng: '22.060999',
      population: ''
    },
    {
      city: 'Vónitsa',
      admin: 'Dytikí Elláda',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '38.916611',
      lng: '20.890417',
      population: ''
    },
    {
      city: 'Síndos',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.669752',
      lng: '22.806046',
      population: ''
    },
    {
      city: 'Kíssamos',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.494289',
      lng: '23.652784',
      population: ''
    },
    {
      city: 'Almyrós',
      admin: 'Thessalía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '39.181541',
      lng: '22.758519',
      population: ''
    },
    {
      city: 'Chálki',
      admin: 'Notío Aigaío',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '36.222649',
      lng: '27.611277',
      population: ''
    },
    {
      city: 'Ptolemaḯda',
      admin: 'Dytikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.512124',
      lng: '21.678029',
      population: ''
    },
    {
      city: 'Níkaia',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.973675',
      lng: '23.640226',
      population: ''
    },
    {
      city: 'Nigríta',
      admin: 'Kentrikí Makedonía',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '40.907565',
      lng: '23.500116',
      population: ''
    },
    {
      city: 'Áno Viánnos',
      admin: 'Kríti',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '35.053924',
      lng: '25.409959',
      population: ''
    },
    {
      city: 'Glyfáda',
      admin: 'Attikí',
      country: 'Greece',
      population_proper: '',
      iso2: 'GR',
      capital: 'minor',
      lat: '37.863716',
      lng: '23.754249',
      population: ''
    }
  ]